board/urls.py
from django.urls import path
from .views import (PostListView,
                    PostDetailView,
					PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
					PostTestView
                   )

app_name = 'board'

urlpatterns = [
		path('', PostListView.as_view() , name='notice-board' ),
		path('posts/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
		path('posts/new', PostCreateView.as_view(), name='post-create'),
		path('posts/<int:pk>/edit/', PostUpdateView.as_view(), name='post-update'),
		path('posts/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

		path('posts/js', PostTestView.as_view(), name='post-test'),
		]

test_baord/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('notice-board/', include('board.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    post_date = models.DateField(auto_now_add=True)
    post_edited = models.DateTimeField(auto_now=True)
    post_created = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='upload_files/', max_length=100, null=True, blank=True, default=None)

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        return reverse('board:post-detail', kwargs={'pk': self.pk})
        #return reverse('board:notice-board')

    class Meta:
        ordering = ('post_created',)

board/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    #file = forms.FileField(required=False)
    class Meta:
        model = Post
        fields = ('title', 'author', 'body', 'file')
        widgets = {
            'title': forms.TextInput(),
            'author': forms.TextInput(),
            'body': forms.Textarea(),
            'file': forms.FileField(),
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'file')
        widgets = {
            'title': forms.TextInput(),
            'body': forms.Textarea(),
            'file': forms.FileField(),
        }

board/views.py
from django.urls import reverse_lazy
from django.views.generic import (ListView, DetailView, CreateView, UpdateView, DeleteView
                                  )
from .models import Post
from .filters import PostFilter
from .forms import PostForm, EditForm

class PostListView(ListView):
    model = Post
    template_name = 'notice_board/post_list.html'
    # context_object_name = 'posts'
    ordering = ['-post_created']
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        filter = PostFilter(self.request.GET, queryset)
        return filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        filter = PostFilter(self.request.GET, queryset)
        context["filter"] = filter
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'notice_board/post_detail.html'
    context_object_name = 'post'


class PostCreateView(CreateView):
    model = Post
    template_name = 'notice_board/post_form.html'
    fields = '__all__'
    #form_class = PostForm #returns 'FileField' object has no attribute 'use_required_attribute' error


class PostTestView(CreateView):
    model = Post
    template_name = 'notice_board/form_js_test.html'
    fields = '__all__'


class PostUpdateView(UpdateView):
    model = Post
    fields = '__all__'
    template_name = 'notice_board/post_form_django.html'
    #template_name = 'notice_board/post_form.html'
    # 빈 폼이 출력됌, post_form_django.html의 form.html의 html 요소가 post_form과 동일해서 작동은 됐음.

class PostDeleteView(DeleteView):
    model = Post
    template_name = 'notice_board/post_confirm_delete.html'
    success_url = reverse_lazy('board:notice-board')

templates/notice_board/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Notice Board</title>
    <meta charset="UTF-8">
    {% block css %}
    {% endblock css %}
    <link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/earlyaccess/nanummyeongjo.css">
</head>
<body>
   <div id="warp">
        <div id="header">
        </div>
        <div id="content">
            <h1>  <a href="{% url 'board:notice-board' %}"> Notice Board </a></h1>
            <div class="container">
                {% block content %}
                {% endblock content %}
                <br><br>
            </div>
        </div>
    </div>
</body>
</html>

templates/notice_board/form_js_test.html
{% extends './base.html' %}
{% load static %}

{% block css %}
{% endblock css %}

{% block content %}
    <h2> Post </h2>
     <form name="jsform" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="editor">
                <p>title <input type="text" name="title_text" id= "title_text" size="50" placeholder="Enter title" required=""/>
                    <span id="span_title"></span></p>
                <textarea name="body_text" id="body_text" cols="50" rows="10" placeholder="Enter content"></textarea>

                <br><br>
                <input type="button" id="hw" value="Hello world" />
            </div>

            <div class="submit">
                <input type="submit" name="btnsubmit"  value="submit" onclick="return validate()"/>
            </div>
     </form>
    <style type="text/css">
    span {
        color:red;
    }
    </style>

    <script type="text/javascript">
        function validate() {
           // alert("hi");
            var title = document.getElementById("title_text").value;
            var body = document.getElementById("body_text").value;

            if(title == "")
            {
                document.getElementById("span_title").innerHTML="Invalid title"
                //alert("Empty title");
                return false;

            }
            if(body == "")
            {
                alert("Emtpy content");
                return false;
            }
        }



        var hw = document.getElementById('hw');
        hw.addEventListener('click', function(){
            alert('Hello world');
        })
    </script>






{% endblock content %}

templates/notice_board/post_confirm_delete.html
{% extends './base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'posts/css/post_confirm_delete.css' %}">
{% endblock css %}

{% block content %}
<div class="confirm">
    <p class="title">Post: [{{post.title}}]</p>
    <p>Are you sure you want to delete this post?</p>
    <form method="POST">{% csrf_token %}
        <div class="confirm_btn">
            <input type="submit" value="Delete">
        </div>
    </form>
</div>
{% endblock content %}

templates/notice_board/post_detail.html
{% extends './base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'posts/css/post_detail.css' %}">
{% endblock css %}

{% block post_header %}
    <div class="container">
        <h1 class="title">{{post.title}}</h1>
        <p class="date">{{post.date_created}}</p>
    </div>
{% endblock post_header %}

{% block content %}
    <div class="content">
        <div class="container">
        <h2 class="title">{{post.title}}</h2>
        <p class="date">{{post.author}}</p>
        <p class="date">{{post.post_date}}</p>
        <hr>

        <p class="text">{{post.body|linebreaksbr}}</p>
        <p class="file"> To check if file is uploaded: {{post.file}}</p>
        <hr>

        </div>
    </div>
    <div class="btn">
        <div class="btn_list"><a href="{% url 'board:notice-board' %}">Back to list</a></div>
        <div class="right-btn">
            <div class="btn_modify"><a href="{% url 'board:post-update' post.id %}">Edit</a></div>
            <div class="btn_delete"><a href="{% url 'board:post-delete' post.id %}">Delete</a></div>
        </div>
    </div>
{% endblock content %}



                <h2 class="title">{{post.title}}</h2></a>
                    <p class="author">{{ post.author.username }}</p>
                    <p class="date">{{ post.post_date }}</p>
                    <p class="text">{{post.body|slice:":100"}}</p>

templates/notice_board/post_form.html
{% extends './base.html' %}

{% block content %}
<div class="container">
    <h2> POST </h2>
        <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
            <div class="editor">
                 <br>
{# FORM FIELDS  #}
                <p>title <input type="text" name="title" maxlength="100" placeholder="Enter title" required="required" id="id_title">
                        <span id="span_title"></span></p>

                <p>author <select name="author" required="" id="id_author">
                <option value="" selected="">---------</option>
                <option value="1">dayeon-board</option>
                </select> <span id="span_author"></span></p></p>
                <p><textarea name="body" cols="40" rows="10" required="" id="id_body" placeholder="Enter content"></textarea></p>
                <p><input type="file" name="file" id="id_file"></p>
            </div>
{# SUBMIT BUTTON#}
            <div class="submit">

{#                <input type="submit" value="post">#}
                <input type="reset" value="reset">
                <input type="submit" name="btnsubmit"  value="submit" onclick="return validate()"/>
            </div>
        </form>
    <div class="btn_back">
        <br><br>
        <a href="/notice-board/">Return to post list</a>
    </div>
</div>

{# CSS #}
    <style type="text/css">
    span {
        color:red;
    }
    </style>

{# JAVA SCRIPT #}
    <script type="text/javascript">
    {# FORM FIELDS#}
        function validate() {
           // alert("hi");
            var title = document.getElementById("id_title").value;
            var body = document.getElementById("id_body").value;
            var author = document.getElementById("id_author").value;


            if(title == "")
            {
                document.getElementById("span_title").innerHTML="Empty title: please write something"
                //alert("Empty title");
                return false;

            }
            if(body == "")
            {
                alert("Emtpy content: please write something");
                return false;
            }

            if(author == "")
            {
                document.getElementById("span_author").innerHTML="Empty author: Please select the author"
                //alert("Please select the author");
                return false;
            }
        }

    </script>

{% endblock content %}

templates/notice_board/post_form_django.html
{% extends './base.html' %}
{% load static %}

{% block css %}

{% endblock css %}

{% block post_header %}
    <div class="container">
        <h1>글쓰기</h1>
    </div>
{% endblock post_header %}

{% block content %}
    <h1> Post </h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="editor">
                <p>{{form.title}}</p>
                {% for error in form.title.errors %}
                    <p class="error">{{error}}</p>
                {% endfor %}
                <p>{{form.author}}</p>
                <p>{{form.body}}</p>
                {% for error in form.body.errors %}
                    <p class="error">{{error}}</p>
                {% endfor %}
                <p>{{form.file}}</p>
            </div>
            <div class="submit">
                <input type="submit" value="post">
            </div>
        </form>
    <div class="btn_back">
        <a href="{% url 'board:notice-board' %}" >Return to post list</a>
    </div>
{% endblock content %}

templates/notice_board/post_form_feedback.html
{% extends './base.html' %}

{% block content %}
<div class="container">
    <h2> POST feedback ver</h2>
        <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
            <div class="editor">
                 <br>
{# FORM FIELDS  #}
                <p>title <input type="text" name="title" maxlength="100" placeholder="Enter title" required="required" id="title">
                        <span id="span_title"></span></p>

                <p>author <select name="author" required="" id="author">
                <option value="" selected="">---------</option>
                <option value="1">dayeon-board</option>
                </select> <span id="span_author"></span></p></p>
                <p><textarea name="body" cols="40" rows="10" required="" id="body" placeholder="Enter content"></textarea></p>
                <p><input type="file" name="file" id="file"></p>
            </div>
{# SUBMIT BUTTON#}
            <div class="submit">

{#                <input type="submit" value="post">#}
                <input type="reset" value="reset">
                <input type="submit" name="btnsubmit"  value="submit" />
            </div>
        </form>
    <div class="btn_back">
        <br><br>
        <a href="/notice-board/">Return to post list</a>
    </div>
</div>

{# CSS #}
    <style type="text/css">
    span {
        color:red;
    }
    </style>

{# JAVA SCRIPT #}
    <script type="text/javascript">
    {# FORM FIELDS#}
    window.addEventListener("load", function(){
    let form = document.querySelector("form");
    form.addEventListener("submit", function(event) {
    let title = document.querySelector("input[name=title]");

    if(title.value === ""){
        alert("타이틀 입력");
        title.focus();
        return false;
    }
    });
    });

    </script>

{% endblock content %}

templates/notice_board/post_form_test.html
{% extends './base.html' %}

{% block content %}

<div class="container">
    <h2> Post </h2>
        <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
            <div class="editor">
                <input type="button" id="hw" value="Hello world"/>
                 <br><br><br>
                <p>title <input type="text" name="title_text" maxlength="100" placeholder="Enter title"
                                required="" id="title_text"/><span id="span_title"></span></p>

                <p>author <select name="author" required="" id="id_author">
                <option value="" selected="">---------</option>
                <option value="1">dayeon-board</option>
                </select></p>
                <textarea name="body_text" id="body_text" cols="50" rows="10" placeholder="Enter content" required=""></textarea>
                </textarea>
                <p><input type="file" name="file" id="id_file"></p>
            </div>
            <div class="submit">
                <input type="submit" value="post">
                <input type="submit" name="btnsubmit"  value="js submit" onclick="return validate()"/>
            </div>
        </form>
        <div class="btn_back">
            <br>
            <a href="/notice-board/">Return to post list</a>
        </div>
</div>

<style type="text/css">
    span {
        color:red;
    }
    </style>

    <script type="text/javascript">
        function validate() {
           // alert("hi");
            var title = document.getElementById("title_text").value;
            var body = document.getElementById("body_text").value;

            if(title == "")
            {
                document.getElementById("span_title").innerHTML=" Invalid title"
                //alert("Empty title");
                return false;

            }
            if(body == "")
            {
                alert("Emtpy content");
                return false;
            }
        }

        var hw = document.getElementById('hw');
        hw.addEventListener('click', function(){
            alert('Hello world');
        })
    </script>

{% endblock content %}

templates/notice_board/post_list.html
{% extends './base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'object_list/css/post_list.css' %}">
{% endblock css %}

{% block content %}
    <!-- post list -->
    <div class="btn_post">
        <h3>Post List | <a href="{% url 'board:post-create'%}">Post</a> </h3>
        <hr>
    </div>

    {% if object_list.exists %}
        <div class="post_container">
            {% for post in object_list %}
                <div class="post"><a href="{% url 'board:post-detail' post.id %}">
                    <h2 class="title">{{post.title}}</h2></a>
                    <p class="author">{{ post.author.username }}</p>
                    <p class="date">{{ post.post_date }}</p>
                    <p class="text">{{post.content}}</p>
                </div>
            {% endfor %}
        </div>

        <div class="paginator">
        <hr>
            {% if page_obj.has_previous %}
                <a href="?page=1" class="first">first</a>
                <a href="?page={{page_obj.previous_page_number}}" class="prev">prev</a>
            {% endif %}

            <span class="page">
                <p>{{page_obj.number}} of {{page_obj.paginator.num_pages}}</p>
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}" class="next">next</a>
                <a href="?page={{page_obj.paginator.num_pages}}" class="last">last</a>
            {% endif %}
        </div>
        <br>

    {% else %}
        <div class="blank">
            <p>No post yet.</p>
        </div>
    {% endif %}

<!-- FILTER -->
    <h3>Search</h3>
    <form method="get" class="form-style">
        <div class="bytitle">
            <label for="id_title__icontains">by Title</label>
            <input type="text" name="title__icontains" class="form-control is-valid form-style" placeholder="enter text" title="" id="id_title__icontains">
        </div>

        <div class="bybody">
            <label for="id_body__icontains">by content</label>
            <input type="text" name="body__icontains" class="form-control is-valid" placeholder="enter text" title="" id="id_body__icontains">
        </div>

            <br>
            <div class="button">
                <input type="submit" name="btnsubmit"  value="search">
                <input type="reset" value="reset">
                <a href="{% url 'board:notice-board' %}">Back to list</a>
            </div>
    </form>
</div>

{% endblock content %}